//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinktecture.ServiceModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thinktecture.ServiceModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied..
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found multiple ServiceThrottles.  ObjectPoolingAttribute is incompatible with other code that customizes throttles..
        /// </summary>
        internal static string ExDifferentThrottle {
            get {
                return ResourceManager.GetString("ExDifferentThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found multiple ServiceThrottles. ObjectPoolingAttribute is incompatible with other code that customizes throttles..
        /// </summary>
        internal static string ExDifferentThrottle1 {
            get {
                return ResourceManager.GetString("ExDifferentThrottle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FlatWsdl extension does not support multiple WSDLs. Make sure the same xml namespace is used for data contracts, message contracts, service contracts, service behavior and binding..
        /// </summary>
        internal static string ExInconsistantXmlNamespaces {
            get {
                return ResourceManager.GetString("ExInconsistantXmlNamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstanceContextMode must not be set to Single..
        /// </summary>
        internal static string ExInvalidContext {
            get {
                return ResourceManager.GetString("ExInvalidContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstanceContextMode must not be set to Single..
        /// </summary>
        internal static string ExInvalidContext1 {
            get {
                return ResourceManager.GetString("ExInvalidContext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinPoolSize must be less than MaxPoolSize on ObjectPoolingAttribute..
        /// </summary>
        internal static string ExMinLargerThanMax {
            get {
                return ResourceManager.GetString("ExMinLargerThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinPoolSize must be less than MaxPoolSize on ObjectPoolingAttribute..
        /// </summary>
        internal static string ExMinLargerThanMax1 {
            get {
                return ResourceManager.GetString("ExMinLargerThanMax1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool size values must be positive integers..
        /// </summary>
        internal static string ExNegativePoolSize {
            get {
                return ResourceManager.GetString("ExNegativePoolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool size values must be positive integers..
        /// </summary>
        internal static string ExNegativePoolSize1 {
            get {
                return ResourceManager.GetString("ExNegativePoolSize1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found null ServiceThrottle.  ObjectPoolingAttribute must run after ServiceThrottlingBehavior..
        /// </summary>
        internal static string ExNullThrottle {
            get {
                return ResourceManager.GetString("ExNullThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found null ServiceThrottle. ObjectPoolingAttribute must run after ServiceThrottlingBehavior..
        /// </summary>
        internal static string ExNullThrottle1 {
            get {
                return ResourceManager.GetString("ExNullThrottle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectPoolingAttribute appears before ServiceThrottlingBehavior in ServiceHost.Description.Behaviors, but ObjectPoolingAttribute depends on ServiceThrottlingBehavior.  Either remove one of these behaviors or reorder them..
        /// </summary>
        internal static string ExThrottleBeforePool {
            get {
                return ResourceManager.GetString("ExThrottleBeforePool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectPoolingAttribute appears before ServiceThrottlingBehavior in ServiceHost.Description.Behaviors, but ObjectPoolingAttribute depends on ServiceThrottlingBehavior.  Either remove one of these behaviors or reorder them..
        /// </summary>
        internal static string ExThrottleBeforePool1 {
            get {
                return ResourceManager.GetString("ExThrottleBeforePool1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New object created in the pool..
        /// </summary>
        internal static string MsgNewObject {
            get {
                return ResourceManager.GetString("MsgNewObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New object created in the pool..
        /// </summary>
        internal static string MsgNewObject1 {
            get {
                return ResourceManager.GetString("MsgNewObject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object returned and added to the pool..
        /// </summary>
        internal static string MsgObjectPooled {
            get {
                return ResourceManager.GetString("MsgObjectPooled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object returned and added to the pool..
        /// </summary>
        internal static string MsgObjectPooled1 {
            get {
                return ResourceManager.GetString("MsgObjectPooled1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object is being removed from the pool..
        /// </summary>
        internal static string MsgObjectRemoving {
            get {
                return ResourceManager.GetString("MsgObjectRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object is being removed from the pool..
        /// </summary>
        internal static string MsgObjectRemoving1 {
            get {
                return ResourceManager.GetString("MsgObjectRemoving1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied parameter is not an ICommunicationObject..
        /// </summary>
        internal static string NoCommunicationObject {
            get {
                return ResourceManager.GetString("NoCommunicationObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No custom binding section for WCF defined..
        /// </summary>
        internal static string NoCustomBindingConfig {
            get {
                return ResourceManager.GetString("NoCustomBindingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied parameter is not a valid Action delegate..
        /// </summary>
        internal static string NoValidDelegate {
            get {
                return ResourceManager.GetString("NoValidDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied parameter is not a valid Exception..
        /// </summary>
        internal static string NoValidException {
            get {
                return ResourceManager.GetString("NoValidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF configuration is not available..
        /// </summary>
        internal static string NoWCFConfig {
            get {
                return ResourceManager.GetString("NoWCFConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- {0} called.
        /// </summary>
        internal static string OperationCalled {
            get {
                return ResourceManager.GetString("OperationCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application setting &apos;retries&apos; could not be found..
        /// </summary>
        internal static string RetriesNotFound {
            get {
                return ResourceManager.GetString("RetriesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}::{1} called.
        /// </summary>
        internal static string ServiceAndOperationCalled {
            get {
                return ResourceManager.GetString("ServiceAndOperationCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application setting &apos;timeToWait&apos; could not be found..
        /// </summary>
        internal static string TimeToWaitNotFound {
            get {
                return ResourceManager.GetString("TimeToWaitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong WCF binding name: binding configuration for &apos;{0}&apos; could not be found.
        /// </summary>
        internal static string WrongBindingName {
            get {
                return ResourceManager.GetString("WrongBindingName", resourceCulture);
            }
        }
    }
}
