//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.CodeDom.Compiler;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;

[GeneratedCode("System.ServiceModel", "3.0.0.0")]
[ServiceContract(ConfigurationName="IDummyService")]
public interface IDummyService
{
    [OperationContract(Action="http://tempuri.org/IDummyService/DoSomething",
        ReplyAction="http://tempuri.org/IDummyService/DoSomethingResponse")]
    string DoSomething(string value);
}

[GeneratedCode("System.ServiceModel", "3.0.0.0")]
public interface IDummyServiceChannel : IDummyService, IClientChannel
{
}

[DebuggerStepThrough()]
[GeneratedCode("System.ServiceModel", "3.0.0.0")]
public partial class SvcUtilGeneratedClient : ClientBase<IDummyService>, IDummyService
{
    public SvcUtilGeneratedClient()
    {
    }

    public SvcUtilGeneratedClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public SvcUtilGeneratedClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public SvcUtilGeneratedClient(string endpointConfigurationName, EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public SvcUtilGeneratedClient(Binding binding, EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    #region IDummyService Members

    public string DoSomething(string value)
    {
        return base.Channel.DoSomething(value);
    }

    #endregion
}